CREATE TABLE IF NOT EXISTS users
(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    username TEXT NOT NULL UNIQUE,
    password TEXT,
    enabled INTEGER NOT NULL DEFAULT FALSE,
    admin INTEGER NOT NULL DEFAULT FALSE,
    autoapprove INTEGER NOT NULL DEFAULT FALSE,
    approver INTEGER NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS workers
(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    owner INTEGER NOT NULL,
    name TEXT NOT NULL,
    enabled INTEGER NOT NULL DEFAULT TRUE,
    key TEXT NOT NULL
);
